### ISSUE TITLE
Chart canvas/context becomes null until a few redraws later

### ISSUE THREAD

**Issue by ThenTech** [sgratzl/chartjs-chart-graph#79] opened 2023-09-06 10:51 UTC
As mentioned [here](https://github.com/chartjs/Chart.js/issues/11295#issuecomment-1708090219), I get the same error `Cannot read properties of null (reading 'addEventListener')` when using this plugin with `react-chartjs-2`. When rendering a `tree` type graph, at some point the `chart.canvas` reference becomes `null` thus throwing the error in `createProxyAndListen` from `ChartJS`.

If I add `redraw={true}` to the `react-chartjs-2` `Chart` wrapper, and force it to recreate the graph every time, it does seem to work, but still throws the error 2 times.

I am not sure if I'm missing something else or where exactly the problem originates.

**To Reproduce**

Use `react-chartjs-2`'s Chart and create a `tree` type chart.

**Expected behavior**

I expect the tree to be rendered the first time around.

**Context**

- Version:
```
"chart.js": "4.4.0",
"react-chartjs-2": "5.2.0",
"chartjs-chart-graph": "4.2.3",
```
- Browser: Chrome 116.0.5845.141

**Comment by sgratzl** [comment] 2023-09-09 06:22
can you reproduce the same problem with other chart.js chart types or just with this plugin?

**Comment by wualvinhardyangkasa** [comment] 2023-10-04 09:56
I also experienced the same error `Cannot read properties of null (reading 'addEventListener')` with my own chart.js wrapper. 

- Version:
"chart.js": "^4.4.0",
"chartjs-chart-graph": "^4.2.5",

Here's the code that reproduce the problem:
https://codesandbox.io/p/sandbox/jolly-dew-vx64kl?file=%2Fapp%2Fpage.tsx%3A1%2C1

**Comment by sgratzl** [comment] 2023-10-09 01:11
should be fixed with the latest patch release. 

The problem was that the async chart update after the layout process was done didn't check whether the chart was destroyed or not

**Closed by sgratzl** 2023-10-09 01:11 UTC
Labels: bug

**Comment by ThenTech** [comment] 2023-10-09 07:41
That was it exactly. I can confirm that error is not thrown any more in the `v4.2.6`
